export type Snippet = { id: string; title: string; lang: string; code: string; desc: string };

export const SNIPPETS: Snippet[] = [
  {
    id: "enhance-eq",
    title: "تحسين السطوع/التباين/التشبع",
    lang: "ffmpeg",
    desc: "Adjust brightness, contrast, saturation",
    code: "ffmpeg -i input.mp4 -vf eq=brightness=0.06:contrast=1.15:saturation=1.2 -c:a copy out.mp4",
  },
  {
    id: "unsharp",
    title: "زيادة الحدّة (Unsharp Mask)",
    lang: "ffmpeg",
    desc: "Sharpen the image",
    code: "ffmpeg -i input.mp4 -vf unsharp=5:5:1.0:5:5:0.0 -c:a copy out.mp4",
  },
  {
    id: "denoise-hqdn3d",
    title: "إزالة الضوضاء hqdn3d",
    lang: "ffmpeg",
    desc: "Denoise with hqdn3d",
    code: "ffmpeg -i input.mp4 -vf hqdn3d=4:3:6:4.5 -c:a copy out.mp4",
  },
  {
    id: "denoise-nlmeans",
    title: "إزالة ضوضاء قوية nlmeans",
    lang: "ffmpeg",
    desc: "Stronger denoise (slow)",
    code: "ffmpeg -i input.mp4 -vf nlmeans=10:7:5:3:3 -c:a copy out.mp4",
  },
  {
    id: "upscale",
    title: "ترقية الدقة إلى 1080p (lanczos)",
    lang: "ffmpeg",
    desc: "Upscale to 1920x1080",
    code: "ffmpeg -i input.mp4 -vf scale=1920:1080:flags=lanczos -c:a copy out.mp4",
  },
  {
    id: "fps",
    title: "تغيير الإطارات إلى 60fps",
    lang: "ffmpeg",
    desc: "Change frame rate",
    code: "ffmpeg -i input.mp4 -filter:v fps=60 -c:a copy out.mp4",
  },
  {
    id: "trim",
    title: "قص مقطع من الفيديو",
    lang: "ffmpeg",
    desc: "Trim a clip (start at 5s, length 10s)",
    code: "ffmpeg -ss 5 -i input.mp4 -t 10 -c copy out.mp4",
  },
  {
    id: "speed",
    title: "تسريع الفيديو والصوت 2x",
    lang: "ffmpeg",
    desc: "Speed up 2x",
    code: "ffmpeg -i input.mp4 -filter_complex [0:v]setpts=0.5*PTS[v];[0:a]atempo=2.0[a] -map [v] -map [a] out.mp4",
  },
  {
    id: "reverse",
    title: "عكس الفيديو",
    lang: "ffmpeg",
    desc: "Reverse video",
    code: "ffmpeg -i input.mp4 -vf reverse -af areverse out.mp4",
  },
  {
    id: "extract-audio",
    title: "استخراج الصوت MP3",
    lang: "ffmpeg",
    desc: "Extract audio as MP3",
    code: "ffmpeg -i input.mp4 -vn -acodec libmp3lame -q:a 2 out.mp3",
  },
  {
    id: "remove-audio",
    title: "إزالة الصوت",
    lang: "ffmpeg",
    desc: "Strip audio",
    code: "ffmpeg -i input.mp4 -c copy -an out.mp4",
  },
  {
    id: "replace-audio",
    title: "استبدال الصوت بمقطع آخر",
    lang: "ffmpeg",
    desc: "Replace audio track (upload music.mp3 first)",
    code: "ffmpeg -i input.mp4 -i music.mp3 -map 0:v -map 1:a -c:v copy -shortest out.mp4",
  },
  {
    id: "normalize-audio",
    title: "تطبيع مستوى الصوت (loudnorm)",
    lang: "ffmpeg",
    desc: "Normalize loudness (EBU R128)",
    code: "ffmpeg -i input.mp4 -af loudnorm=I=-16:TP=-1.5:LRA=11 -c:v copy out.mp4",
  },
  {
    id: "audio-denoise",
    title: "إزالة ضوضاء الصوت (afftdn)",
    lang: "ffmpeg",
    desc: "Audio denoise",
    code: "ffmpeg -i input.mp4 -af afftdn=nf=-25 -c:v copy out.mp4",
  },
  {
    id: "fade-in-out",
    title: "تلاشي بداية ونهاية",
    lang: "ffmpeg",
    desc: "Fade in/out video and audio (assumes 10s clip)",
    code: "ffmpeg -i input.mp4 -vf fade=in:0:30,fade=out:240:30 -af afade=in:st=0:d=1,afade=out:st=8:d=2 out.mp4",
  },
  {
    id: "watermark-text",
    title: "إضافة نص (علامة مائية)",
    lang: "ffmpeg",
    desc: "Burn-in text watermark",
    code: "ffmpeg -i input.mp4 -vf drawtext=text='Lovable':fontcolor=white:fontsize=36:x=20:y=20 -c:a copy out.mp4",
  },
  {
    id: "remove-logo-delogo",
    title: "إزالة شعار بسيطة (delogo)",
    lang: "ffmpeg",
    desc: "Cover a logo region by interpolation",
    code: "ffmpeg -i input.mp4 -vf delogo=x=10:y=10:w=120:h=40 -c:a copy out.mp4",
  },
  {
    id: "crop",
    title: "اقتصاص الفيديو",
    lang: "ffmpeg",
    desc: "Crop to 1280x720 from (100,50)",
    code: "ffmpeg -i input.mp4 -vf crop=1280:720:100:50 -c:a copy out.mp4",
  },
  {
    id: "rotate",
    title: "تدوير 90°",
    lang: "ffmpeg",
    desc: "Rotate 90 clockwise",
    code: "ffmpeg -i input.mp4 -vf transpose=1 -c:a copy out.mp4",
  },
  {
    id: "concat",
    title: "دمج فيديوهات",
    lang: "ffmpeg",
    desc: "Concatenate two clips (upload input2.mp4 first)",
    code: "ffmpeg -i input.mp4 -i input2.mp4 -filter_complex [0:v][0:a][1:v][1:a]concat=n=2:v=1:a=1[v][a] -map [v] -map [a] out.mp4",
  },
  {
    id: "thumbnail",
    title: "التقاط صورة في ثانية محددة",
    lang: "ffmpeg",
    desc: "Grab a thumbnail at 2s",
    code: "ffmpeg -ss 2 -i input.mp4 -frames:v 1 thumb.jpg",
  },
  {
    id: "gif",
    title: "تحويل إلى GIF",
    lang: "ffmpeg",
    desc: "Make a GIF (10fps, 480 wide)",
    code: "ffmpeg -i input.mp4 -vf fps=10,scale=480:-1:flags=lanczos out.gif",
  },
  {
    id: "compress",
    title: "ضغط بجودة عالية (H.264 CRF 23)",
    lang: "ffmpeg",
    desc: "Re-encode with CRF",
    code: "ffmpeg -i input.mp4 -c:v libx264 -crf 23 -preset veryfast -c:a aac -b:a 128k out.mp4",
  },
  {
    id: "py-moviepy",
    title: "MoviePy: قص ودمج (Python)",
    lang: "python",
    desc: "Local Python example (run on your machine)",
    code: "from moviepy.editor import VideoFileClip, concatenate_videoclips\na = VideoFileClip('a.mp4').subclip(0, 5)\nb = VideoFileClip('b.mp4').subclip(0, 5)\nconcatenate_videoclips([a, b]).write_videofile('out.mp4')",
  },
  {
    id: "node-fluent",
    title: "fluent-ffmpeg (Node.js)",
    lang: "javascript",
    desc: "Run ffmpeg from Node",
    code: "import ffmpeg from 'fluent-ffmpeg';\nffmpeg('input.mp4')\n  .videoFilters('eq=brightness=0.1:contrast=1.2')\n  .save('out.mp4');",
  },
  {
    id: "bash-batch",
    title: "Bash: معالجة دفعة كاملة",
    lang: "bash",
    desc: "Loop over files",
    code: "for f in *.mp4; do\n  ffmpeg -i \"$f\" -vf eq=brightness=0.05:contrast=1.1 \"out_$f\"\ndone",
  },
  {
    id: "powershell-batch",
    title: "PowerShell: معالجة دفعة",
    lang: "powershell",
    desc: "Windows batch loop",
    code: "Get-ChildItem *.mp4 | ForEach-Object {\n  ffmpeg -i $_.Name -vf \"eq=brightness=0.05:contrast=1.1\" \"out_$($_.Name)\"\n}",
  },
];