export type Snippet = { id: string; title: string; lang: string; code: string; desc: string };

export const SNIPPETS: Snippet[] = [
  // ── FFmpeg: تحسين الجودة ──────────────────────────────────────────────────
  {
    id: "enhance-eq",
    title: "تحسين السطوع / التباين / التشبع",
    lang: "ffmpeg",
    desc: "ضبط شامل لجودة الصورة",
    code: "ffmpeg -i input.mp4 -vf eq=brightness=0.06:contrast=1.15:saturation=1.2:gamma=1.0 -c:a copy out.mp4",
  },
  {
    id: "unsharp",
    title: "زيادة الحدّة (Unsharp Mask)",
    lang: "ffmpeg",
    desc: "تحسين حدة الصورة",
    code: "ffmpeg -i input.mp4 -vf unsharp=5:5:1.0:5:5:0.0 -c:a copy out.mp4",
  },
  {
    id: "denoise-hqdn3d",
    title: "إزالة الضوضاء hqdn3d (سريع)",
    lang: "ffmpeg",
    desc: "تنعيم الصورة وإزالة الحبيبات",
    code: "ffmpeg -i input.mp4 -vf hqdn3d=4:3:6:4.5 -c:a copy out.mp4",
  },
  {
    id: "denoise-nlmeans",
    title: "إزالة ضوضاء قوية nlmeans",
    lang: "ffmpeg",
    desc: "جودة أعلى — أبطأ للملفات الكبيرة",
    code: "ffmpeg -i input.mp4 -vf nlmeans=10:7:5:3:3 -c:a copy out.mp4",
  },
  {
    id: "enhance-full",
    title: "تحسين شامل (حدة + ألوان + ضوضاء)",
    lang: "ffmpeg",
    desc: "مزيج من كل تحسينات الجودة",
    code: "ffmpeg -i input.mp4 -vf \"eq=brightness=0.05:contrast=1.1:saturation=1.15,unsharp=5:5:0.8,hqdn3d=3:2:4:3\" -c:a copy -preset veryfast out.mp4",
  },
  {
    id: "color-grade",
    title: "تصحيح الألوان الاحترافي",
    lang: "ffmpeg",
    desc: "curves + vibrance",
    code: "ffmpeg -i input.mp4 -vf \"eq=brightness=0.02:contrast=1.08:saturation=1.1:gamma=0.95,curves=r='0/0 0.5/0.52 1/1':g='0/0 0.5/0.50 1/1':b='0/0 0.5/0.48 1/0.98'\" -c:a copy out.mp4",
  },
  // ── FFmpeg: دقة وإطارات ──────────────────────────────────────────────────
  {
    id: "upscale-1080",
    title: "ترقية الدقة إلى 1080p",
    lang: "ffmpeg",
    desc: "upscale بخوارزمية lanczos",
    code: "ffmpeg -i input.mp4 -vf scale=1920:1080:flags=lanczos -c:a copy out.mp4",
  },
  {
    id: "upscale-4k",
    title: "ترقية إلى 4K",
    lang: "ffmpeg",
    desc: "ترقية عالية الدقة",
    code: "ffmpeg -i input.mp4 -vf scale=3840:2160:flags=lanczos -c:a copy out.mp4",
  },
  {
    id: "fps-60",
    title: "تغيير معدل الإطارات إلى 60fps",
    lang: "ffmpeg",
    desc: "سلاسة حركة أعلى",
    code: "ffmpeg -i input.mp4 -filter:v fps=60 -c:a copy out.mp4",
  },
  {
    id: "fps-24",
    title: "تحويل إلى 24fps (سينمائي)",
    lang: "ffmpeg",
    desc: "معدل الأفلام السينمائية",
    code: "ffmpeg -i input.mp4 -filter:v fps=24 -c:a copy out.mp4",
  },
  // ── FFmpeg: قص، تسريع، تأثيرات ──────────────────────────────────────────
  {
    id: "trim",
    title: "قص مقطع من الفيديو",
    lang: "ffmpeg",
    desc: "من الثانية 5 لمدة 10 ثوانٍ",
    code: "ffmpeg -ss 5 -i input.mp4 -t 10 -c copy out.mp4",
  },
  {
    id: "speed-2x",
    title: "تسريع الفيديو 2x",
    lang: "ffmpeg",
    desc: "تضاعف السرعة مع الصوت",
    code: "ffmpeg -i input.mp4 -filter_complex \"[0:v]setpts=0.5*PTS[v];[0:a]atempo=2.0[a]\" -map [v] -map [a] out.mp4",
  },
  {
    id: "speed-half",
    title: "تبطيء الفيديو 0.5x",
    lang: "ffmpeg",
    desc: "slow motion",
    code: "ffmpeg -i input.mp4 -filter_complex \"[0:v]setpts=2.0*PTS[v];[0:a]atempo=0.5[a]\" -map [v] -map [a] out.mp4",
  },
  {
    id: "reverse",
    title: "عكس الفيديو والصوت",
    lang: "ffmpeg",
    desc: "قلب الفيديو من النهاية للبداية",
    code: "ffmpeg -i input.mp4 -vf reverse -af areverse out.mp4",
  },
  {
    id: "rotate-90",
    title: "تدوير 90° يمين",
    lang: "ffmpeg",
    desc: "تصحيح اتجاه الفيديو",
    code: "ffmpeg -i input.mp4 -vf transpose=1 -c:a copy out.mp4",
  },
  {
    id: "flip-h",
    title: "قلب أفقي (مرآة)",
    lang: "ffmpeg",
    desc: "عكس الصورة أفقياً",
    code: "ffmpeg -i input.mp4 -vf hflip -c:a copy out.mp4",
  },
  {
    id: "crop",
    title: "اقتصاص الفيديو",
    lang: "ffmpeg",
    desc: "اقتصاص 1280x720 من الإحداثي (100,50)",
    code: "ffmpeg -i input.mp4 -vf crop=1280:720:100:50 -c:a copy out.mp4",
  },
  {
    id: "concat",
    title: "دمج فيديوهين",
    lang: "ffmpeg",
    desc: "ارفع input2.mp4 أولاً ثم نفّذ",
    code: "ffmpeg -i input.mp4 -i input2.mp4 -filter_complex \"[0:v][0:a][1:v][1:a]concat=n=2:v=1:a=1[v][a]\" -map [v] -map [a] out.mp4",
  },
  {
    id: "thumbnail",
    title: "التقاط صورة عند ثانية محددة",
    lang: "ffmpeg",
    desc: "حفظ إطار كـ JPG",
    code: "ffmpeg -ss 3 -i input.mp4 -frames:v 1 thumb.jpg",
  },
  {
    id: "gif",
    title: "تحويل إلى GIF",
    lang: "ffmpeg",
    desc: "10fps بعرض 480px",
    code: "ffmpeg -i input.mp4 -vf fps=10,scale=480:-1:flags=lanczos out.gif",
  },
  {
    id: "compress",
    title: "ضغط الفيديو H.264",
    lang: "ffmpeg",
    desc: "CRF 23 — متوازن بين الجودة والحجم",
    code: "ffmpeg -i input.mp4 -c:v libx264 -crf 23 -preset veryfast -c:a aac -b:a 128k out.mp4",
  },
  {
    id: "compress-high",
    title: "ضغط شديد (حجم أصغر)",
    lang: "ffmpeg",
    desc: "CRF 28 — جودة أقل، حجم أصغر بكثير",
    code: "ffmpeg -i input.mp4 -c:v libx264 -crf 28 -preset veryfast -c:a aac -b:a 96k out.mp4",
  },
  {
    id: "fade-in-out",
    title: "تلاشي الفيديو بداية ونهاية",
    lang: "ffmpeg",
    desc: "fade in/out بصري وصوتي",
    code: "ffmpeg -i input.mp4 -vf \"fade=in:0:25,fade=out:225:25\" -af \"afade=in:st=0:d=1,afade=out:st=9:d=1\" out.mp4",
  },
  // ── FFmpeg: الصوت ────────────────────────────────────────────────────────
  {
    id: "extract-audio",
    title: "استخراج الصوت كـ MP3",
    lang: "ffmpeg",
    desc: "جودة عالية VBR",
    code: "ffmpeg -i input.mp4 -vn -acodec libmp3lame -q:a 2 out.mp3",
  },
  {
    id: "extract-wav",
    title: "استخراج الصوت كـ WAV",
    lang: "ffmpeg",
    desc: "صوت غير مضغوط — جودة كاملة",
    code: "ffmpeg -i input.mp4 -vn -acodec pcm_s16le -ar 44100 out.wav",
  },
  {
    id: "remove-audio",
    title: "إزالة الصوت من الفيديو",
    lang: "ffmpeg",
    desc: "نسخ الفيديو بدون صوت",
    code: "ffmpeg -i input.mp4 -c copy -an out.mp4",
  },
  {
    id: "replace-audio",
    title: "استبدال الصوت بملف آخر",
    lang: "ffmpeg",
    desc: "ارفع music.mp3 أولاً",
    code: "ffmpeg -i input.mp4 -i music.mp3 -map 0:v -map 1:a -c:v copy -shortest out.mp4",
  },
  {
    id: "normalize-audio",
    title: "تطبيع مستوى الصوت (EBU R128)",
    lang: "ffmpeg",
    desc: "loudnorm — معيار البث",
    code: "ffmpeg -i input.mp4 -af loudnorm=I=-16:TP=-1.5:LRA=11 -c:v copy out.mp4",
  },
  {
    id: "audio-denoise",
    title: "إزالة ضوضاء الصوت (afftdn)",
    lang: "ffmpeg",
    desc: "تنقية الصوت من الضجيج الخلفي",
    code: "ffmpeg -i input.mp4 -af afftdn=nf=-25 -c:v copy out.mp4",
  },
  {
    id: "volume-up",
    title: "رفع مستوى الصوت +6dB",
    lang: "ffmpeg",
    desc: "تضخيم الصوت",
    code: "ffmpeg -i input.mp4 -af volume=6dB -c:v copy out.mp4",
  },
  {
    id: "bass-boost",
    title: "تعزيز الجهير (Bass Boost)",
    lang: "ffmpeg",
    desc: "زيادة الترددات المنخفضة",
    code: "ffmpeg -i input.mp4 -af \"equalizer=f=100:t=o:w=200:g=8\" -c:v copy out.mp4",
  },
  {
    id: "treble-boost",
    title: "تعزيز الحدة (Treble Boost)",
    lang: "ffmpeg",
    desc: "زيادة الترددات العالية",
    code: "ffmpeg -i input.mp4 -af \"equalizer=f=8000:t=o:w=4000:g=6\" -c:v copy out.mp4",
  },
  {
    id: "echo-effect",
    title: "إضافة صدى (Echo)",
    lang: "ffmpeg",
    desc: "تأثير reverb خفيف",
    code: "ffmpeg -i input.mp4 -af \"aecho=0.8:0.88:500:0.5\" -c:v copy out.mp4",
  },
  {
    id: "pitch-up",
    title: "رفع طبقة الصوت (نبرة أعلى)",
    lang: "ffmpeg",
    desc: "+4 semitones تقريباً",
    code: "ffmpeg -i input.mp4 -af \"asetrate=44100*1.26,aresample=44100\" -c:v copy out.mp4",
  },
  {
    id: "pitch-down",
    title: "خفض طبقة الصوت (نبرة أعمق)",
    lang: "ffmpeg",
    desc: "-4 semitones تقريباً",
    code: "ffmpeg -i input.mp4 -af \"asetrate=44100*0.79,aresample=44100\" -c:v copy out.mp4",
  },
  // ── FFmpeg: العلامات المائية والبصمة ─────────────────────────────────────
  {
    id: "watermark-text",
    title: "إضافة نص كعلامة مائية",
    lang: "ffmpeg",
    desc: "نص ثابت في الزاوية",
    code: "ffmpeg -i input.mp4 -vf \"drawtext=text='My Watermark':fontcolor=white@0.7:fontsize=28:x=20:y=20\" -c:a copy out.mp4",
  },
  {
    id: "remove-logo-delogo",
    title: "إزالة شعار بـ delogo",
    lang: "ffmpeg",
    desc: "إزالة احترافية بالاستيفاء — بدون أثر",
    code: "ffmpeg -i input.mp4 -vf delogo=x=10:y=10:w=150:h=50 -c:a copy out.mp4",
  },
  {
    id: "blur-region",
    title: "طمس منطقة محددة",
    lang: "ffmpeg",
    desc: "تمويه وجه أو شعار",
    code: "ffmpeg -i input.mp4 -vf \"boxblur=enable='between(x,50,200)*between(y,30,100)':luma_radius=15:luma_power=2\" -c:a copy out.mp4",
  },
  {
    id: "strip-metadata",
    title: "حذف جميع البيانات الوصفية",
    lang: "ffmpeg",
    desc: "إزالة EXIF والـ metadata كاملاً",
    code: "ffmpeg -i input.mp4 -map_metadata -1 -c copy out_clean.mp4",
  },
  {
    id: "fingerprint-change",
    title: "تغيير البصمة الرقمية كاملاً",
    lang: "ffmpeg",
    desc: "إعادة تشفير + إزالة metadata + ضوضاء خفية",
    code: "ffmpeg -i input.mp4 -map_metadata -1 -metadata title=\"\" -vf noise=alls=2:allf=t+u -c:v libx264 -crf 22 -preset veryfast -c:a aac -b:a 128k out_new.mp4",
  },
  {
    id: "subtitle-burn",
    title: "حرق ترجمة في الفيديو",
    lang: "ffmpeg",
    desc: "دمج ملف SRT في الصورة (ارفع sub.srt)",
    code: "ffmpeg -i input.mp4 -vf subtitles=sub.srt out.mp4",
  },
  // ── Python ───────────────────────────────────────────────────────────────
  {
    id: "py-moviepy-trim",
    title: "Python — قص بـ MoviePy",
    lang: "python",
    desc: "تشغّل على جهازك المحلي مع ffmpeg مثبّت",
    code: "from moviepy.editor import VideoFileClip\nclip = VideoFileClip('input.mp4').subclip(5, 15)\nclip.write_videofile('out.mp4')",
  },
  {
    id: "py-moviepy-concat",
    title: "Python — دمج فيديوهات بـ MoviePy",
    lang: "python",
    desc: "concat عدة مقاطع",
    code: "from moviepy.editor import VideoFileClip, concatenate_videoclips\na = VideoFileClip('a.mp4').subclip(0, 5)\nb = VideoFileClip('b.mp4').subclip(0, 5)\nconcatenate_videoclips([a, b]).write_videofile('out.mp4')",
  },
  {
    id: "py-ffmpeg-python",
    title: "Python — ffmpeg-python wrapper",
    lang: "python",
    desc: "API pythonic لـ FFmpeg",
    code: "import ffmpeg\n(\n  ffmpeg\n  .input('input.mp4')\n  .video.filter('eq', brightness=0.1, contrast=1.2)\n  .output('out.mp4')\n  .run()\n)",
  },
  {
    id: "py-subprocess",
    title: "Python — تشغيل FFmpeg بـ subprocess",
    lang: "python",
    desc: "تحكم كامل عبر subprocess",
    code: "import subprocess\nsubprocess.run([\n  'ffmpeg', '-i', 'input.mp4',\n  '-vf', 'eq=brightness=0.1:contrast=1.2',\n  '-c:a', 'copy', 'out.mp4'\n], check=True)",
  },
  {
    id: "py-audio-pydub",
    title: "Python — معالجة صوت بـ pydub",
    lang: "python",
    desc: "تطبيع وتصدير صوت",
    code: "from pydub import AudioSegment\naudio = AudioSegment.from_file('input.mp4')\nnormalized = audio.normalize()\nnormalized.export('out.mp3', format='mp3', bitrate='320k')",
  },
  {
    id: "py-watermark-remove",
    title: "Python — إزالة علامة مائية بـ OpenCV",
    lang: "python",
    desc: "inpainting بـ OpenCV",
    code: "import cv2\nimport numpy as np\nimg = cv2.imread('frame.jpg')\nmask = np.zeros(img.shape[:2], np.uint8)\nmask[10:60, 10:160] = 255\nresult = cv2.inpaint(img, mask, 3, cv2.INPAINT_TELEA)\ncv2.imwrite('clean.jpg', result)",
  },
  // ── JavaScript / Node.js ─────────────────────────────────────────────────
  {
    id: "node-fluent",
    title: "Node.js — fluent-ffmpeg",
    lang: "javascript",
    desc: "API سلسة لـ FFmpeg في Node",
    code: "const ffmpeg = require('fluent-ffmpeg');\nffmpeg('input.mp4')\n  .videoFilters('eq=brightness=0.1:contrast=1.2')\n  .output('out.mp4')\n  .on('end', () => console.log('Done!'))\n  .run();",
  },
  {
    id: "node-compress",
    title: "Node.js — ضغط الفيديو",
    lang: "nodejs",
    desc: "CRF مع fluent-ffmpeg",
    code: "const ffmpeg = require('fluent-ffmpeg');\nffmpeg('input.mp4')\n  .videoCodec('libx264')\n  .addOption('-crf', '23')\n  .addOption('-preset', 'veryfast')\n  .audioCodec('aac')\n  .audioBitrate('128k')\n  .save('out.mp4')\n  .on('end', () => console.log('Compressed!'));",
  },
  {
    id: "node-thumbnail",
    title: "Node.js — توليد Thumbnail",
    lang: "nodejs",
    desc: "التقاط إطار كصورة",
    code: "const ffmpeg = require('fluent-ffmpeg');\nffmpeg('input.mp4')\n  .screenshots({\n    count: 1,\n    timemarks: ['3'],\n    filename: 'thumb.jpg',\n    folder: './'\n  });",
  },
  // ── Bash ─────────────────────────────────────────────────────────────────
  {
    id: "bash-batch",
    title: "Bash — معالجة مجلد كامل",
    lang: "bash",
    desc: "حلقة for على كل ملفات MP4",
    code: "for f in *.mp4; do\n  ffmpeg -i \"$f\" \\\n    -vf \"eq=brightness=0.05:contrast=1.1,unsharp=5:5:0.5\" \\\n    -c:a copy \\\n    \"enhanced_$f\"\ndone",
  },
  {
    id: "bash-extract-all",
    title: "Bash — استخراج صوت من مجلد",
    lang: "bash",
    desc: "تحويل كل MP4 إلى MP3",
    code: "mkdir -p audio_out\nfor f in *.mp4; do\n  name=\"${f%.mp4}\"\n  ffmpeg -i \"$f\" -vn -q:a 2 \"audio_out/${name}.mp3\"\ndone\necho \"Done! Check audio_out/\"",
  },
  {
    id: "bash-watermark-remove",
    title: "Bash — إزالة شعار من مجلد",
    lang: "bash",
    desc: "delogo على مجموعة ملفات",
    code: "# عدّل الإحداثيات حسب موضع الشعار\nX=10; Y=10; W=150; H=50\nfor f in *.mp4; do\n  ffmpeg -i \"$f\" -vf \"delogo=x=$X:y=$Y:w=$W:h=$H\" \"clean_$f\"\ndone",
  },
  // ── PowerShell ───────────────────────────────────────────────────────────
  {
    id: "ps-batch",
    title: "PowerShell — معالجة دفعة (Windows)",
    lang: "powershell",
    desc: "ForEach-Object مع ffmpeg",
    code: "Get-ChildItem *.mp4 | ForEach-Object {\n  $out = \"enhanced_$($_.Name)\"\n  ffmpeg -i $_.Name `\n    -vf \"eq=brightness=0.05:contrast=1.1\" `\n    -c:a copy $out\n  Write-Host \"Done: $out\"\n}",
  },
  {
    id: "ps-compress",
    title: "PowerShell — ضغط مجلد (Windows)",
    lang: "powershell",
    desc: "تقليل حجم ملفات فيديو",
    code: "Get-ChildItem *.mp4 | ForEach-Object {\n  ffmpeg -i $_.Name `\n    -c:v libx264 -crf 26 -preset veryfast `\n    -c:a aac -b:a 128k `\n    \"compressed_$($_.Name)\"\n}",
  },
  {
    id: "ps-strip-meta",
    title: "PowerShell — حذف metadata (Windows)",
    lang: "powershell",
    desc: "إزالة بيانات الخصوصية من مجلد",
    code: "Get-ChildItem *.mp4 | ForEach-Object {\n  ffmpeg -i $_.Name `\n    -map_metadata -1 `\n    -c copy `\n    \"clean_$($_.Name)\"\n}",
  },
];
