/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatermarkRouteImport } from './routes/watermark'
import { Route as TransformRouteImport } from './routes/transform'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as FingerprintRouteImport } from './routes/fingerprint'
import { Route as EnhanceRouteImport } from './routes/enhance'
import { Route as CaptionsRouteImport } from './routes/captions'
import { Route as BatchRouteImport } from './routes/batch'
import { Route as AudioRouteImport } from './routes/audio'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as IndexRouteImport } from './routes/index'

const WatermarkRoute = WatermarkRouteImport.update({
  id: '/watermark',
  path: '/watermark',
  getParentRoute: () => rootRouteImport,
} as any)
const TransformRoute = TransformRouteImport.update({
  id: '/transform',
  path: '/transform',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const FingerprintRoute = FingerprintRouteImport.update({
  id: '/fingerprint',
  path: '/fingerprint',
  getParentRoute: () => rootRouteImport,
} as any)
const EnhanceRoute = EnhanceRouteImport.update({
  id: '/enhance',
  path: '/enhance',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptionsRoute = CaptionsRouteImport.update({
  id: '/captions',
  path: '/captions',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchRoute = BatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRoute = AudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/audio': typeof AudioRoute
  '/batch': typeof BatchRoute
  '/captions': typeof CaptionsRoute
  '/enhance': typeof EnhanceRoute
  '/fingerprint': typeof FingerprintRoute
  '/library': typeof LibraryRoute
  '/terminal': typeof TerminalRoute
  '/transform': typeof TransformRoute
  '/watermark': typeof WatermarkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/audio': typeof AudioRoute
  '/batch': typeof BatchRoute
  '/captions': typeof CaptionsRoute
  '/enhance': typeof EnhanceRoute
  '/fingerprint': typeof FingerprintRoute
  '/library': typeof LibraryRoute
  '/terminal': typeof TerminalRoute
  '/transform': typeof TransformRoute
  '/watermark': typeof WatermarkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/audio': typeof AudioRoute
  '/batch': typeof BatchRoute
  '/captions': typeof CaptionsRoute
  '/enhance': typeof EnhanceRoute
  '/fingerprint': typeof FingerprintRoute
  '/library': typeof LibraryRoute
  '/terminal': typeof TerminalRoute
  '/transform': typeof TransformRoute
  '/watermark': typeof WatermarkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/audio'
    | '/batch'
    | '/captions'
    | '/enhance'
    | '/fingerprint'
    | '/library'
    | '/terminal'
    | '/transform'
    | '/watermark'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/audio'
    | '/batch'
    | '/captions'
    | '/enhance'
    | '/fingerprint'
    | '/library'
    | '/terminal'
    | '/transform'
    | '/watermark'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/audio'
    | '/batch'
    | '/captions'
    | '/enhance'
    | '/fingerprint'
    | '/library'
    | '/terminal'
    | '/transform'
    | '/watermark'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  AudioRoute: typeof AudioRoute
  BatchRoute: typeof BatchRoute
  CaptionsRoute: typeof CaptionsRoute
  EnhanceRoute: typeof EnhanceRoute
  FingerprintRoute: typeof FingerprintRoute
  LibraryRoute: typeof LibraryRoute
  TerminalRoute: typeof TerminalRoute
  TransformRoute: typeof TransformRoute
  WatermarkRoute: typeof WatermarkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watermark': {
      id: '/watermark'
      path: '/watermark'
      fullPath: '/watermark'
      preLoaderRoute: typeof WatermarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transform': {
      id: '/transform'
      path: '/transform'
      fullPath: '/transform'
      preLoaderRoute: typeof TransformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fingerprint': {
      id: '/fingerprint'
      path: '/fingerprint'
      fullPath: '/fingerprint'
      preLoaderRoute: typeof FingerprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enhance': {
      id: '/enhance'
      path: '/enhance'
      fullPath: '/enhance'
      preLoaderRoute: typeof EnhanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captions': {
      id: '/captions'
      path: '/captions'
      fullPath: '/captions'
      preLoaderRoute: typeof CaptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch': {
      id: '/batch'
      path: '/batch'
      fullPath: '/batch'
      preLoaderRoute: typeof BatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio': {
      id: '/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  AudioRoute: AudioRoute,
  BatchRoute: BatchRoute,
  CaptionsRoute: CaptionsRoute,
  EnhanceRoute: EnhanceRoute,
  FingerprintRoute: FingerprintRoute,
  LibraryRoute: LibraryRoute,
  TerminalRoute: TerminalRoute,
  TransformRoute: TransformRoute,
  WatermarkRoute: WatermarkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
